<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-AJ" failures="2" tests="3" name="Default test(failed)" time="3.1" errors="0" timestamp="2022-03-23T08:51:51 IST">
  <testcase classname="FailedXML_Test.Failed_Test" name="Test1" time="2.018">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method FailedXML_Test.Failed_Test.Test1() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method FailedXML_Test.Failed_Test.Test1() didn't finish within the time-out 2000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="FailedXML_Test.Failed_Test" name="Test4" time="0.002"/>
  <testcase classname="FailedXML_Test.Failed_Test" name="Test3" time="1.019">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method FailedXML_Test.Failed_Test.Test3() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method FailedXML_Test.Failed_Test.Test3() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="FailedXML_Test.Failed_Test" name="Test2" time="0.0">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase classname="FailedXML_Test.Failed_Test" name="Test5" time="0.0">
    <ignored/>
  </testcase> <!-- Test5 -->
  <testcase classname="FailedXML_Test.Failed_Test" name="Test6" time="0.0">
    <ignored/>
  </testcase> <!-- Test6 -->
</testsuite> <!-- Default test(failed) -->
